//
//  Day_03_2022_Tests.swift
//  AdventOfCode2023Tests
//
//  Created by David Taylor on 03/12/2023.
//

import AdventOfCode2023
import Foundation
import XCTest

final class Day032022Tests: XCTestCase {
    // two large compartnemnts
    // items go into one of two
    // puzzle input -> items in each rucksack
    // type identified by a single lowercase or uppercase letter - a and A are different
    // items in rucksack is chars on line
    // rucksack has same number of items in each of two compartments - first half of chars in first, second half in second
    
    func test_part1_prioritize_sampleData() {
        XCTAssertEqual(157, prioritiseRuckSackItems(sampleData))
    }
    
    func test_part1_prioritize_puzzleInput() {
        XCTAssertEqual(7_889, prioritiseRuckSackItems(puzzleInput))
    }
    
    func test_part2_prioritize_sampleData() {
        XCTAssertEqual(70, prioritiseBadges(sampleData))
    }
    
    func test_part2_prioritize_puzzleInput() {
        XCTAssertEqual(2_825, prioritiseBadges(puzzleInput))
    }
    
    let sampleData = """
    vJrwpWtwJgWrhcsFMMfFFhFp
    jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL
    PmmdzqPrVvPwwTWBwg
    wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn
    ttgJtRGJQctTZtZT
    CrZsJsPPZsGzwwsLwLmpwMDw
    """
    
    let puzzleInput = """
    BdbzzddChsWrRFbzBrszbhWMLNJHLLLLHZtSLglFNZHLJH
    nnfMwqpQTMffHlNNLllHnZSS
    cGpcMwfppfqcjcTCBBzWDsDbDrjzWz
    LhfjhcdjcGdhFfdGfdjdvwCCZMvvLvWwMLCLSwZC
    rDnsbmptPmlbQMCrQWQQBZQW
    gltgVPngDPbptPsbPzVgmDldfTdfczThjJJjfMcJdFHjjH
    dGlgDflTLLLrRLTLVdQLcQMnbvHbbFzNNvMbnHHn
    sZjWJJCSjWqfCqSjSmJSbFvCzBMBBzHncHNvMBHN
    twqqwpZwfrlwRwDGDR
    zCGGFTQMQrsNRNGZdR
    cLLQgPDpgcgmvPRHrwBdvrNZ
    glWpmJWQDcJpQnpjSmbhFtMnqFfCVTCFCFFM
    zNZWFNZBFrGTdBcZZBdJTrGrmgvppgDHwHmgVHCHCvCPDjzC
    qtqqPnLSfLwvjvvgvvqH
    MtbLLLQbRfPRfnbnnLMtnsbdBNsrGWNWcNcTBWZrrcrWcJ
    sZwstbbDVlHtbhcrhhZLrRpNQN
    jqGjjFjWnzWGgqWjJJNphnLMRhLhcrhcrSLN
    qCJzFJdvmHvbtpbb
    ZSRsvvQvZpsRQGJghClPCwGPChCP
    FVdMLDdtDRdDcBtmcVFntwgJJTlnNPwJnlTlwlTPgN
    VqttMWFmDbjbzrSWRQ
    TsDSBcwshdwSCrgRWZBvgGRG
    LPVJLqqJbbzpFqwpbvgGRmZPrmZgCvCCfr
    tzJlJzQllFLqtwHhjNSdtthjDhTN
    fsDLDDnwvnSdqLSsFSDfsLpbgVttPMpPNjMWVMNfpjgW
    jhHmBmlrTBBHRPVtMZbppNPPZB
    JmTTrTmjRTJqSQQSFqQw
    HPzZFgPFMCHJCcZMcDQGwpLqPLqppwhGvv
    BrWRqbqRsTSTqNddrVrthLQVwnpwphnvnDnGvGDn
    tSbBfsRbTfqjJqjCqm
    pCqrqzmqZzrmCCvCJwJPBRwJBWBmwWBJ
    VqbqbjFLFfSHnfctBwDdDFTwtRRTDF
    LVcnbjHLSqHnhbSGGppCMMZMphpNrQ
    PhTcTPsSPCMvvhhMRPttbNWfNsWFNfWWtpNw
    rdQrDbJBVVjrBVdLjHHHWNWwfHtzzNtFpZZptppg
    JJVGGdddjDjDJmdjGqqRSbPMTvcRlqnnMlvT
    SqGfTrBlSrrrfGGQvCnqZhZmPPhvJh
    LdVNwgsjdjHmjWwDsDpwsHWtnCnQQQQNnvCnbJZQbNbtZZ
    DjssDHLLVppDssdLspswFLVjzfFMTfSBcTRcrFSBzBTzmGzr
    JSJJqlldpJlcdVWMlgMJrcCjrhzHCwTjHrQzwTzZ
    bBvsGBGNFDNRFNFBRDPsDDHCChhhrZRQQzhjhCjTzWCr
    FvbLFGDDtWDFBnPGFDWGqJMgJpSdVStllttlppVS
    clpBdBQBsqGpQbVdqTTWRTSFgLLggffg
    NzvwmHvZtZZgbDSCLDmfmm
    jPJjthHzNwPvvjwjNzPzztZBlrccpbVGBQhlGBVlrpnpBs
    NmFFGlGmzCrNWHvFmFWCFvQPTdDDlbbdgJPtgbbdPDcc
    RwfBqLwZqffqnPbdDgVQDdtRbT
    hnptqLMMLwqjMMjzSzHmhvNNrvvhhz
    hqVrDdPdVDqjsDrjjqsfrrWlctvHJNLfvNcLHNNZRNZHvfZL
    CSnWQSGBBSnmBnTmSbQbNZZMJNJMccGNHLZNNvNv
    gFnmBmBnTCpwmBbgWVqjPsrsjplVrjlqPr
    vgVgJJCphzFjzbwljwww
    PWmfDgrPrPWlSWqSWlSZ
    rrTHQTGTPHDDHgPrcrcPmDPhdtGvnvNnttJCdJhtGVnpdM
    DDDhNgWNLWgDqDgtgtwSngjVSQdf
    cvFrcGmBrrrCdSfSJQ
    mBHzFFvFzmsBspsFsZqhqbWlWdPDlLHbqZ
    TLNpGpRzwGQLLQRTwdvWdWbdbgdBlblb
    FJDVzZzHfZHVzcHgnvHnvngvvc
    MzDVSmZPPrqhGmCqQqLR
    mqHWcBHVcgsbhhnTrrTg
    fWftGtfJpwJMSdFDLFSGDGFnnNrbrhTNsZnrhTswZZnnsb
    dSftppdSFStLDpQfLjWHQvWBmmqVjCqcVv
    frfNzgvzzzJwJqpRcP
    VdVSnGnHqhDDTdqhdLWmjMTmjMPjPmTsmsmjmR
    BdGLSWtBSWDtVqdSDVGqtSSHFZFZtQbZlZfNgFffrgNrvgrl
    jBVSjsJcLcqqjtgcmRFRNFFzFm
    CnHnWQQGGWnnCnfvCTmZRZgNtfZtNDZPtNDtzl
    mWWGGdmQQWwrHHMBBBhrBVqshBLBSL
    cLtFcllvrslGLcLHVzDZQzzpznWzQtQZ
    TmShfSSPJRRBBfSgmdfBJhDNVpGzVZpzQgZgbWzpnDGp
    BhJPfSqdhqJRdBdPqTJBChvrFlHvvCGCccHsMscvrHvv
    zfddZTpZLzLDfLtDCttdTfZPnlcPcnhjPDnlcjMchDPjnP
    MQsFvFHJsQvmNvvswljgbPbwlwjnmcch
    VFVqvqFQHqVJRVCBLpqTGMzCqtMZ
    PZdVgNdQQcdcZQtGhnHtBlvlvWTnbBHWWH
    CDJmzqFmMmLfqmzFwqfzfwMRvpRbTWBBWDnlnbnWnTNTnB
    zFfffjCqwLJCfrCFjCLCzCMsjSZjQNPhQGVSQQZhsGjGgd
    nbHntnqPQwTHwQVC
    BzfSZSpcBZpzpPhSBjRTCBWTTRWTTTWR
    pvZpzPzNfhddJGmmNnJb
    GwTgWlvbgTwMrbwTrlWvwtHBNtNvBhBtdZcShHDtNS
    PnndmnCmnJFnsmRdmFnnZDhRRScRQQHDtDNtcDQS
    CLffLsmqqpJljVdlpMpWlr
    dPCzBLTSLqmqdSCsmrTDVQjZfjfVVZnZhhhLGQ
    wwFpgvPJNwgPPwvZGnQhbZQQFfQZbf
    WvRwwJpHHgpNMNqdTdCdqrmHBPtm
    DbWwjSGFSFfwGfCwDSSPPjLhgrrLWRJRgggJphLzpJLq
    lQTnMHdcQBvlHMMZBcHHTrbzpdzgqrpLdqzzVRVRVV
    vlvlNlBQvBZTQBnHnQTTBBPwPNCCsfSFmbSFfmGPwFmj
    hGGQtbVjhRqlmqqrmDlpmw
    gPMZsMgdssCPPsvrgZcTZTPSnnLLnBWDwLmwWwBnmWSnWNWB
    TsvgMPdcgCfMdcsZJRQhVfVRVQFFQGtr
    NfpFTTpFNbpZMRFrJMMMCv
    dWJPngDWBtPVBdPVGHZzCGHZrrvZRSMSzv
    WDDDVDPlWnLBVgnsgJmQJNqThNmbjlqbbh
    vnznqvfrzzVzrvvnfVqztBtGbMCdGmCcdccJccCLCcpSSgcL
    RQsDsljDlhssWshHhlhsHTlLbgJLpmgbbcMSpSSbcSJgjd
    WswhhHWlRTsQDwWHTRhsvNVvwqzfVmNBtZNmnzzq
    cjcPfLlQtPsZQlfHZJqVSFdVwmSRRqSSddwDvF
    MgNbBgzgnwdPRFmSPn
    CMGbNNMhCMzzPzBpTNPGBclLcLfsptHQfQlZssLcLf
    slsdfpSlllpTVJJGgGDgHMdV
    wrBQrbQrhQcpbQrhLwRBrjVVgGGPgZMtZMVhgMPMGHPg
    QQwRnrwRbbRcmQmrjRnjpvNsNTNSlTmsTqCSvsNSWz
    GWNwppdHdpmzgPFPCRmlCBPB
    bSrJhJSsMhrJMDPRCPBlwVCtVSLV
    QbsbwqQZvrJhhQrhZZrhchTfnTWGNvWpNnjHGvGjNdGT
    NMZGmnMBWmwmNnGwHrHvHzfrvrVVVj
    pSbDRLgbpJDPpRZRQjjFqVhhDFjDVqfrzv
    sQQscLTZcsTpRsBnmlBcdCMBMtlc
    hwWslbGWbRvLZvcscZ
    gQnmmrNTmSnTfgwDwVwpJvJPJzLqLJTLLvRcZz
    mrmnSrDNNQSmmwdggrrDbHMGhtdtGhGlhtClMGhM
    qQdlGcvDQDQvDdmtPmmmlStbjSrm
    CpNhzWTCTRznBMvwtTjMrHtSvj
    nWzsfZCsBhNpZLgGdQDddvqd
    ggjTjJWDVVVRTwQcZWvchshWhs
    LmFfLfSmBtCttNLfCFBPFNBvvvhrcQdvsrsdSwdqcwrwSw
    CHttltmlPLMHRTgJQDgRDTMb
    RPJgCdhgPPSzvWDcCfGHDcvf
    HbrrwBspTwWDDnqbZjjD
    rQrFsrsstQMQHJdHQm
    GVwQVGBZBNQwsjdNcMMlgJNPgj
    SWFfSzTCSWFCSpgnJLSjpMdc
    FhTbvrzrMrDCVHsVsHGBtHwv
    FsqjjVzFVWFqRRWBssdpNSBHwJpHHJJdddSN
    lQgmhvbTcgTgfhTQhSCFCGJHSlwNtJdGHG
    vgZPbbfMhbTmchhjRFRnsDRPWVqzWz
    cvwfjjcJjqhctvSpCgCFVhrFCrpC
    mRsQmsMlNNzznWQlRnsMRQlSCpLNbpwSSSrwFLDFLLLgFp
    zznlnGlmRmMlPZnGQzMszMRfccTjcBJjtJtJjqTZtfwBTt
    PtCwCCVqbjNNqqvGssPmHGsHMfPH
    dcddcWFDJJJcLczhWQdcDScZvHZgpGfsvMfSmsggSvvnvM
    TTQmTDhdQQzdRwjBVrRwCwBbBr
    BnBsFHCrcnBrMBPSmMSCmrcFqnZLddLhdhdGLvqLqgqnLJJp
    WfjTlNVDTtjzNWTlVMWNlTwTJphdgpvJLGLdgghZvGLpwddq
    zVjbVblVDlNTlbzTzDjllDTzHmHCsmcMHcSBrCBbrHBcBPSC
    ddlcGQlCjQNGQmPLslZTlmTtfT
    MDzMwSwqpzpDRpWRJwgZhttrZmTPfZmrmtrMZZ
    JSqRBpJzwgDDpqDqvpBRdCjbCjQCFCbHvdGPjdHQ
    bwzPwGLZMsbJMPPLGLMQzbhhQRvWWtVqVhgCVtWWQDqt
    HddrHFnFNpVnVLhnvLRV
    NLdrFjHTBrrdjFSpFmNBmSfZMwZMJJfSffbwzwPbczbJ
    QTWSzTTLwTfwflSNJRdvGlRGcNgJBl
    FnmmqrqbBBgRbHGc
    MFZqrCVCqmZCprspFZmnnMsDfzWzDwSfjSwPQPTLhffwBLwj
    npfgFRTZRRnDZLdgRfRrrjcWzGpWGGGQrjjWpP
    vblVbvSShhVzHWjzzlrPWG
    bVwqvCBtShqBhCCtqhNqCJRTTBDFJJLnJgDRWFBnWg
    nHDNQvgvnNZHDnsGcjfNTrTfVrfL
    SRWFSBRLtSFqjTrVVcsVjTSG
    BdBbRttWBdbdWdbppmZlLmgwHvgQvgLZ
    PQRZlpDDptQSclBMGVBdhVFGBMpf
    nnrsTCWjLJsnsSMShhGJfwffwV
    vjzqsjqgSHbbtvHZ
    DgFmbdSDZbPgLbDDmFwZwgLSfccGcGvnvvngsGGnsGMNWsWs
    HqztHHhHVhHjhRRhJtCVBCfNprMWpcMMJfsvvMsGscpG
    tjVtBVTBtHHqCRqtzQwTPSNdSwPTTbPFDdml
    sbmBmHZbRRRmwBmsSjHzRjmSCNFLNLLQNQhFgtQLzNztlrff
    MpqPPDPVnGqrJpcqqJpMVlgtlLFLChCgChCCQgCtCD
    VdcVVJvdrVWHbwHWBSSBRb
    tPDVBzzNSNdDSQpMQMTQJMMQMN
    LqSWSmbsmfQTTGZMWGCW
    cLjLcbrjqmvfqLbfmqLwDBBzSHPzlwzcdBlnnP
    SbnHrGHSrrhHJBrrScDfcPDMfpPGcGcpDL
    QTpmpmmQWlZsTvVQDMgggFLgFcPf
    zsCNlltCslzlTNsNlShwdJCpSqdHrBhpwr
    JZmFrmLGjFZdDGrrVTvzmPVvRRVzwzzl
    WBnfMDBqMsgDBqpBvzwVlCwRTRRPpvlw
    WfghfttggfSnnqbDftfqSBBDQdHhZFFJrrHFjGJdGjFrjQLj
    rNLRjrlVlrFRJzlsjrVlRFGCmnMtftgCNDDgDmCfqNgPNM
    SpdBpdHbpHWhZqnCdtCGggqCPn
    QHHvvWwWhwVVQRscVzGl
    QffLtMQGMQfDMMwMTJwqWHvH
    nSSFznjFcfjTgVJTJjvT
    RrBpcfSNpRBcFshrCtQrDGLPQb
    GctcMldStGwPPbcLsQTV
    jhnzDgnHnnfPVwHQTTLTds
    gBgzDDhzvqdGGvrtdvtm
    PPwRWVTvRvPVLwRpMlzmbmsbHWjbbs
    dFTFCNfdjzjFjsMF
    SgdffSTrnnqCgdqgcNrfSZqVvVLRDPJZQwJBLPQPtLZwJJ
    HSzDQftHphTBHFhr
    WMmJsMJNLWNPmmsncjMJcjtvwggVvhFFFhjrVwrjrjppvT
    WWPsJJCWCtZZZRGC
    SfFZQDRLgpLlRgQRRRFWTsbhBhgTjbWBjhshgw
    tHVNGjtzzHvMMJJhrWJNrTrPbP
    jvVVvGCGtCmjHtdHzQQfDpSSlDRnFfQFmR
    ZBBPfVVPPrVmrWZJzNdPznbnbSzznP
    gvgpGqFFMgMcGgwLwGpcJNZSTZbdbdzNNSlqbTnn
    ssZLgsMLQvcFpVrhCsmtWHjrrW
    nFvhRnWWzBRPHQqcqqCqmFbd
    SJDJgVprLfDfbJmHmWWHQtJW
    wVsgWVSTgLjfSsVjVBRvRNwwGGRhNZhRMZ
    wTRrRBCTPTBPlgMqgHCqggHLgg
    dmDzpQpBdmWmWzzzDFzjGNMSWLSgLVGGLVNSLgSg
    JbFdmQQJpjpptQbdJJmDmdtnZhZRflTlnTrTlrhBwPPc
    jwSwssQbwbStlhRgtsVstn
    zPzFdFFZccPDgntzVHHgghRz
    vVVdfFmZPDMWZZBmGQbwJJGCLwwMwJCS
    PLLffLFqqNLwSffbnVzzRf
    lsmgTggChrgDtZsZVblMVJMznVnwMBnb
    hDZZTmZvhTgstvwNFdqpWQcqvP
    mmWwpwqtmmHTqHpprRZQPPZLZWSFRFRB
    gzcgscgbfvhRRNZQRRQPvr
    JsjhcshCfJgrrpttTCTplH
    TvNrvNrJfWWvtJLTHhvZZhQQwVGZZhbV
    mFCPmBMPlPsPPBsMFPszbHQJwwHHhbZVQVzjhGHZ
    qmlBsdCSmJBmsBBMnMMTDWDNcLrDprSNcWDNrW
    HSnHCVqTddFHSVqFqdStSQGQwRzQCzCRzGRRGNPQwz
    jhlBpgNvlfZjlfvmpgfgfBrMRRwMMPPLQMZRPMWMMZPQ
    hflfpgjfBfDcpchlpvndbHFDdHqSqNVqNVdn
    QBfhlVNfHSZHfVCVHSQfZfTCctdvdDTRtjDCtTRsjsvj
    brrWWqzFWzwWbswDchhTRtDhjT
    gbrFLnpzqrWPgqpLWrhnHGZlSfLfHfQBGVfHHNVG
    hcFmVScmQBVhtcvfHLfvHSnbHRLn
    lzQqlDqgpWPvJfRnlNJvww
    PjCCCPgDgqGzmMtCQstZmBFs
    GrnrHrmVVFMFhSSbSfhR
    zjTqLtBjjdWdWTLshMZMDbPNRMSSqSPNfD
    dTWjdtwWhjWTBzcnrpcwmQpCwcpw
    BgtVBsgVVJhgGsSGJbghJqbsjLfZmLjmmtfZndNNZFFZNLdm
    MHTlzlwHSvPvzMSPCTMQCNZdjjmnfQjdZfNLjF
    HMDTwPDpzrTzpScBghDbVqRBgRBJsR
    qjCsTmrrnnCmhcFrCjqmThRlbHGvJGvvvbRbbJRcQJRG
    fVBBTfMdSZLNZgPdgglGRdbtbtJRllJWJtWb
    TSZZSpNMPBLgpZLVgppBDFhzDmjrnzhjssFqDhzFnn
    MDtDMWmMQmdzmMMqvlGfRcjzgpcPPjczPl
    sZsHJWNJFJNbWFBhFBnnbVclbVVPglfcRggffGGpjl
    srHWLNZZJdSLSdvDMw
    BFqsPnsZcgnncggccqsqqpDPtDWPpPNTNSNThrWtSj
    dQbfQQJJdwdmFRbJLRJdMrfDWrjpDrrprhDDDDNWWD
    QGwdJmCFJZvGsvvncB
    GRRNSjrffGTSPrNTffSgcJTwWJZbbZvwvwtVwWVJZv
    CMcFsqmBQzMzshsBQBQvLWmJVwZtpJLJwJLvwt
    qBzChnQlzMcRSnnRRjHGGg
    dPPbPWNdTBbDpHPHpNsgzvFlglvHzvSFzCFF
    fntqhGhRMhnnnGGCVMRhCVlSjswFvvjzjSzvQVSgsl
    MMqqJJRCnMhZLCRhtPNrpZPDDWTDTrNBmD
    VjVGNTNlNchVjNGRWrSWWtZtRrzncR
    BTbbbwDmCDLTbDwfHmzZMmRrWtzPrZSZtrrz
    qDLLqvwLBsfBbBdQFQTJhqThVTQJ
    qBqPBGZflhrWznzZZdsnzv
    FmHRcCCsCDwDbjtzdjWbdz
    cTRwCCNHFNmwRgmFTNCFTJqqfqPJsPhPBlsrsfGf
    JTNhhNrCTcWpJJcpWw
    LLdLsfMsdStbtggLbnTpwfWDzpjvnnjzcz
    MqSZsgbMbGFbZtgTSZSFSLhhmHlBQlmrmrPHHCPPZPBr
    GgjjgpGvpJJtjgvPrJttsLjVwCsQsQNLsfLfMVCl
    RddqZqzcZdSWcHdcqQfQLMwVflfNQNMQ
    FncWTRcFlHWFmcFTgPJhGvDgpnnhhGtG
    ZGPFJsPQCbZCCbgz
    nrvrnGWTwwqTBRcpCRRg
    DnGWDldNmSLSMdMQ
    ScDmPPPmjmjjWgtdSmdmCnNqVQVVrNRTZTQTQDHHZGNH
    wbbMhLvMJpRwJQrJGHqQGrQHqr
    wzhspwpppswsMFLmtnzjdcmdPRWPtS
    fPlLTtBlTjDbWcTMJcncWqss
    LdvLrLpCRRQQmvhhVNpwRMWJZcFMZWJwJFFFwZsGcs
    prrRVpvvRVNmRvvzHjHPlzPLSffbbPHS
    bbCbzsQbBzbBFbFzFfJHfVJPfVPtzZttpm
    hwvrjDDwjcDcvdnNvwdnwwDPpNtNMVtPpJpRmVMPfmtVZR
    mmqDWjhcqhwvDDdTsSGGCbQGSBBLTGGl
    wthtwrBQhhSrqJJVLMRPPtJLPF
    vbmbZqfqgsfHmcllmLLJNLJMNFJNNvPGJn
    jHlDscllClCCgbZzhWqBzBQzprWCqS
    DwpDlwDwllhJwbDFNDwFPhDnQnZZzVVnnBrtNznzSSzZrr
    MHPfWRTgWzTQmSTTZt
    GdPjHLRMCfcGvwqDGbFq
    NGdNpDPdNGLppLpwSNFFFDLwnnZbMnrHlHZQcHbcnHQcPcQM
    jBgBsjssgjWJVGhBfhvJVnMlbnZQVrrrlHCcCZrl
    sRBgvRffhhtvtBgvjgttWBJTLmFLLwdwzFdqLDDDqFGdLFTd
    RBzRGRGBgnrPJrRGGWWbDggZTSTVZVFFSVZZdw
    tfmLhjfshNNsqpppfjHdwVdQZbVbQFVVTmSVDV
    jvqtwHqCNLNsNhNfjssLCzGJWcBRJRBCBBBrrWnGrG
    cGDBdNFdNdDStNtGdGQGscDMvZjjZWMvMLjsjjLZjLsJLv
    fbRnRzHVPClfRlbbmfHRlPvZvMLpqjvZJqZMpzMpZjBZ
    gfbfBgCHCPVNhNGgTtFDcF
    ljjvLZvvllFnlLJLJjLWFQrVssFpsGMFpNMGsr
    qbHSqHTcHChqCmTSRqqBVpVdBQsVQQGHdMprWV
    DbtcCqRhhTRmDnPMlLgfgztlZZ
    QtMQzPZcbtGgTtLvtf
    HwcDsdVVDnNSGLhwvffJvfTT
    CSsdSHNmSDHcCqqcrrzQcC
    nDNDfmMnmDJRNfJJdMDRBdwjcTtsSHvBTswTjwLtsCts
    QcbQrZZggGWVVWbZZjStswCSCCttGCwLvC
    ZgZgbzVglVbchVVrVhFWWpnnpNJmJMqDfMJnMRqNDDMD
    WMfNvsjWGjsqFjqTRRQVJztDzVmJHbft
    ZPhplcrLrmzQGzmz
    ZPddLPlcSclhZChndMvgTjjWNGWMGWBj
    nDLjMchghDcljfjffpfsqTmGCTGszGZVVzHV
    wdFJPFrQRwSNbjVQCTGsHZHmHCHs
    BRJJSddvdBrJwrBRNRFRSPRjvclLpWhpglgWpLplltnMgh
    BbVRzMcpbMNMHMTJmWdljdlJjT
    GtsqFnfvGSFqGfQvgnWWZlLlLjZWtWldPmlT
    sSsFqsqsGghwQQmfGRHbbVczbwwBpBpHcw
    BBFCBJCsGJBBgvgsvTlVhgNg
    ZnLdjRQddLRnZrlScHRVTTSHhRvg
    fnnjZLWdrnqdWrrPLddqVqBzGDJJFGCBDfJmbDzFMbmB
    """
}
